[package]
name = "analyzer"
version = "0.1.0"
authors = ["Anton Katekov <anton.katekov@tri-ad.global>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
